version: "3.9"
services:

  app-nodejs:
    container_name: syntNodejs
    build: .
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/src

  mariadb:
    container_name: mariaDbSyntNodejs
    image: mariadb
    restart: always
    ports:
      - 3315:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - dbmariadb:/var/lib/mysql

volumes:
  dbmariadb:
